// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CreatProjectInput struct {
	ID string `json:"id"`
}

type CreateVersionInput struct {
	ProjectID     string `json:"projectId"`
	InformationID string `json:"informationId"`
}
