version: "3.7"

services:
  database.gui:
    image: fenglc/pgadmin4
    ports:
      - 8081:5050
    environment:
      - DEFAULT_USER=postgres
      - DEFAULT_PASSWORD=postgres
    networks:
      - services
  database:
    container_name: bec.database
    hostname: db
    image: postgres:11
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bec
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - services
volumes:
  pgdata:
    driver: local
networks:
  services:
