version: "3.7"

services:
  database:
    container_name: bec.database
    hostname: db
    command: start --insecure
    image: cockroachdb/cockroach:v1.1.3
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bec
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "26257:26257"
      - "3030:8080"
    volumes:
      - pgdata:/cockroach/cockroach-data
    networks:
      - services
volumes:
  pgdata:
    driver: local
networks:
  services:
