version: "3.7"

services:
  project-service:
    command: /bin/bash -c "go run ./main.go"
    image: golang:1.12.6-stretch
    volumes:
      - ./services/project:/usr/service:rw
    working_dir: /usr/service
    container_name: project
    hostname: project
    restart: always
    ports:
      - "5050:5050"
    networks:
      - services
  database:
    container_name: database
    hostname: db
    command: start --insecure
    image: cockroachdb/cockroach:v1.1.3
    restart: on-failure
    ports:
      - "3030:8080"
    volumes:
      - cockdata:/cockroach/cockroach-data
    networks:
      - services
volumes:
  cockdata:
    driver: local
networks:
  services:
