version: '3.7'

services:
  bec.service.project:
    command: /bin/bash -c "go run ./main.go"
    container_name: bec.service.project
    hostname: project
    image: golang:1.12.6-stretch
    volumes:
      - ./project-service:/usr/project-service:rw
    working_dir: /usr/project-service
    ports:
      - 5050:5050
    environment:
      - DB_CONFIG=postgresql://postgres:postgres@database/bec?sslmode=disable
      - DB_CLEAN_START=false
    networks:
      - services
  bec.service.healthcheck:
    command: /bin/bash -c "go run ./main.go"
    container_name: bec.service.healthcheck
    hostname: healthcheck
    image: golang:1.12.6-stretch
    volumes:
      - ./healthcheck:/usr/healthcheck:rw
    working_dir: /usr/healthcheck
    ports:
      - 5060:5050
    environment:
      - DB_CONFIG=postgresql://postgres:postgres@database/bec?sslmode=disable
      - DB_CLEAN_START=false
    networks:
      - services
  bec.service.component:
    command: /bin/bash -c "go run ./main.go"
    container_name: bec.service.component
    hostname: project
    image: golang:1.12.6-stretch
    volumes:
      - ./component-service:/usr/component-service:rw
    working_dir: /usr/component-service
    ports:
      - 5051:5051
    environment:
      - DB_CONFIG=postgresql://postgres:postgres@database/bec?sslmode=disable
      - DB_CLEAN_START=false
    networks:
      - services
  database.gui:
    image: fenglc/pgadmin4
    ports:
      - 8081:5050
    environment:
      - DEFAULT_USER=postgres
      - DEFAULT_PASSWORD=postgres
    networks:
      - services
  database:
    container_name: bec.database
    hostname: db
    image: postgres:11
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bec
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - services
  rabbitmq:
    container_name: bec.rabbit
    hostname: rabbit
    image: rabbitmq:3.7.5-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - services
volumes:
  pgdata:
    driver: local
networks:
  services: