version: '3.4'

services:
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client/Dockerfile
    networks:
      - database
    depends_on:
      - server.api
      - server.grpc

  server.api:
    image: ${DOCKER_REGISTRY-}serverapi
    hostname: rest
    build:
      context: .
      dockerfile: Server.API/Dockerfile
    networks:
      - database

  server.grpc:
    image: ${DOCKER_REGISTRY-}servergrpc
    container_name: server.grpc
    hostname: grpc
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Server.gRPC/Dockerfile
    networks:
      - database

networks:
  database:
    external: true
