version: "3.5"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    networks:
      - database
      - server

  web:
    build:
      context: ./web
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./web/src:/web/src
    ports:
      - "8080:3000"
    networks:
      - server

  db:
    container_name: ced_db
    build: ./db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ced
    ports:
      - '5440:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database

networks:
  server:
    driver: bridge

  database:
    driver: bridge

volumes: 
  pgdata: 
    driver: local