version: "3.5"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    networks:
      - ced_database

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=ced
    ports:
      - "5440:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - ced_database

volumes:
  pgdata-dev:
    driver: local

networks:
  ced_database:
    driver: bridge
