version: "3.5"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8000"
      - "2345:2345"
    environment:
      - port=8000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
  db:
    container_name: db
    image: postgres:12.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ced
    ports:
      - '5440:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database

volumes:
  pgdata:
    driver: local

networks:
  database:
    driver: bridge
