version: "3.7"

services:
  project:
    container_name: project
    hostname: project
    command: /bin/bash -c "go run ./main.go -mod=vendor"
    image: golang:1.13-stretch
    volumes:
      - ./services/project:/usr/service:rw
    working_dir: /usr/service
    restart: always
    networks:
      - services
      - database

  # database:
  #   container_name: database
  #   hostname: database
  #   image: postgres:12.1
  #   restart: on-failure
  #   environment:
  #     - POSTGRES_PASSWORD=supersecret
  #     - POSTGRES_USER=admin
  #     - POSTGRES_DB=bec
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - pgnet

  component:
    container_name: component
    hostname: component
    command: /bin/bash -c "go run ./main.go -mod=vendor"
    image: golang:1.13-stretch
    volumes:
      - ./services/component:/usr/service:rw
    working_dir: /usr/service
    restart: always
    networks:
      - services
      - database

  proxy:
    image: nginx:1.17.6
    container_name: proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - services

# volumes:
#   pgdata:
#     driver: local

networks:
  services:
  database:
    external: true
