version: "3.5"

services:
  server:
    build:
      context: ./server
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./server:/go/src/github.com/lilahamstern/ced/server
    ports:
      - "5000:8080"
    networks:
      - database
      - server
      - monitor

  web:
    build:
      context: ./web
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./web/src:/web/src
    ports:
      - "8080:3000"
    networks:
      - server

  db:
    container_name: ced_db
    build: ./db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ced
    ports:
      - '5440:5432'
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    networks:
      - database
      - monitor

  grafana:
    container_name: ced_grafana
    image: grafana/grafana:7.1.0
    environment:
      - GF_USERS_ALLOW_SIGNUP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor

volumes:
  grafana_data:
    driver: local

networks:
  monitor:
    driver: bridge

  server:
    driver: bridge

  database:
    driver: bridge
