version: "3.5"
services:
  # server:
  #   image: cosmtrek/air
  #   working_dir: "/go/src/github.com/lilahamstern/ced"
  #   configs:
  #     - ./sercer/.air.toml
  #   ports:
  #     - "5000:5000"
  #   security_opt:
  #     - "seccomp:unconfined"
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./server:/go/src/github.com/lilahamstern/ced
  #   networks:
  #     - ced_database

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=ced
    ports:
      - "5440:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - ced_database

volumes:
  pgdata-dev:
    driver: local

networks:
  ced_database:
    driver: bridge
