basePath: /space
host: localhost:5000
info:
  contact:
    email: leo.ronnebro@hamsterapps.net
    name: Author
    url: http://www.hamsterapps.net
  description: Offical CED Rest API docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CED Rest API
  version: "0.1"
paths:
  /space/projects/{id}:
    get:
      consumes:
      - application/json
      description: Fetch singel project by id
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: Fetch singel project by id
swagger: "2.0"
