migrate:
	migrate -source file://internal/repository/database/migrations/postgres -database ${CED_DB} $(args)

#migrate -source file://internal/repository/database/migrations/postgres -database postgres://dev:dev@127.0.0.1:5440/ced?sslmode=disable up 