// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatProjectInput struct {
	ID int64 `json:"id"`
}

type CreateVersionInput struct {
	ProjectID     string `json:"projectId"`
	InformationID string `json:"informationId"`
}
