version: '3.4'

services:
  #server.api:
  #image: ${DOCKER_REGISTRY-}serverapi
  #hostname: server-api
  #container_name: server-api
  #build:
  # context: .
  #dockerfile: Server.API/Dockerfile
  #networks:
  #- database

  server.grpc:
    image: ${DOCKER_REGISTRY-}servergrpc
    hostname: server-grpc
    container_name: server-grpc
    stdin_open: true
    tty: true
    build:
      context: ../server
      dockerfile: Server.gRPC/Dockerfile
    networks:
      - database

networks:
  database:
    external: true
