GET http://localhost:8080/api/projects/info

###

POST http://localhost:8080/api/projects
content-type: application/json

{
    "pid": "41ssa2332dwa",
    "uid": "3812934731sa2da",
    "name": "SKitdaw",
    "client": "SSAB3123",
    "sector": "Foretag3123",
    "ua": "byggarebob123",
    "desc": "En liten t123est byggnad"
}

###s

GET http://localhost:8080/api/projects
###