
GET http://localhost:8080/api/projects/info

###

POST http://localhost:8080/api/projects
content-type: application/json

{
    "pid": "41ssa2332dwa",
    "oid": "3812934731sa2da",
    "name": "Uppdatering",
    "client": "SSAB3123",
    "sector": "Foretag3123",
    "manager": "byggarebob123",
    "description": "En liten t123est byggnad"
}

###s

GET http://localhost:8080/api/projects
###